/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedValidatorRouteImport } from './routes/_authenticated/validator'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedTradeCreatorRouteImport } from './routes/_authenticated/trade-creator'
import { Route as AuthenticatedStrategyProfilesRouteImport } from './routes/_authenticated/strategy-profiles'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMetafundRouteImport } from './routes/_authenticated/metafund'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommandCenterRouteImport } from './routes/_authenticated/command-center'
import { Route as AuthenticatedTradeDetailIdRouteImport } from './routes/_authenticated/trade-detail.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedValidatorRoute = AuthenticatedValidatorRouteImport.update({
  id: '/validator',
  path: '/validator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradeCreatorRoute =
  AuthenticatedTradeCreatorRouteImport.update({
    id: '/trade-creator',
    path: '/trade-creator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStrategyProfilesRoute =
  AuthenticatedStrategyProfilesRouteImport.update({
    id: '/strategy-profiles',
    path: '/strategy-profiles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetafundRoute = AuthenticatedMetafundRouteImport.update({
  id: '/metafund',
  path: '/metafund',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandCenterRoute =
  AuthenticatedCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTradeDetailIdRoute =
  AuthenticatedTradeDetailIdRouteImport.update({
    id: '/trade-detail/$id',
    path: '/trade-detail/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/metafund': typeof AuthenticatedMetafundRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/strategy-profiles': typeof AuthenticatedStrategyProfilesRoute
  '/trade-creator': typeof AuthenticatedTradeCreatorRoute
  '/validator': typeof AuthenticatedValidatorRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/trade-detail/$id': typeof AuthenticatedTradeDetailIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/metafund': typeof AuthenticatedMetafundRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/strategy-profiles': typeof AuthenticatedStrategyProfilesRoute
  '/trade-creator': typeof AuthenticatedTradeCreatorRoute
  '/validator': typeof AuthenticatedValidatorRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/trade-detail/$id': typeof AuthenticatedTradeDetailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/metafund': typeof AuthenticatedMetafundRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/strategy-profiles': typeof AuthenticatedStrategyProfilesRoute
  '/_authenticated/trade-creator': typeof AuthenticatedTradeCreatorRoute
  '/_authenticated/validator': typeof AuthenticatedValidatorRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/trade-detail/$id': typeof AuthenticatedTradeDetailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/command-center'
    | '/dashboard'
    | '/journal'
    | '/metafund'
    | '/profile'
    | '/strategy-profiles'
    | '/trade-creator'
    | '/validator'
    | '/community'
    | '/trade-detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/command-center'
    | '/dashboard'
    | '/journal'
    | '/metafund'
    | '/profile'
    | '/strategy-profiles'
    | '/trade-creator'
    | '/validator'
    | '/community'
    | '/trade-detail/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/command-center'
    | '/_authenticated/dashboard'
    | '/_authenticated/journal'
    | '/_authenticated/metafund'
    | '/_authenticated/profile'
    | '/_authenticated/strategy-profiles'
    | '/_authenticated/trade-creator'
    | '/_authenticated/validator'
    | '/_authenticated/community'
    | '/_authenticated/trade-detail/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trade-creator': {
      id: '/_authenticated/trade-creator'
      path: '/trade-creator'
      fullPath: '/trade-creator'
      preLoaderRoute: typeof AuthenticatedTradeCreatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategy-profiles': {
      id: '/_authenticated/strategy-profiles'
      path: '/strategy-profiles'
      fullPath: '/strategy-profiles'
      preLoaderRoute: typeof AuthenticatedStrategyProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metafund': {
      id: '/_authenticated/metafund'
      path: '/metafund'
      fullPath: '/metafund'
      preLoaderRoute: typeof AuthenticatedMetafundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/validator': {
      id: '/_authenticated/validator'
      path: '/validator'
      fullPath: '/validator'
      preLoaderRoute: typeof AuthenticatedValidatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trade-detail/$id': {
      id: '/_authenticated/trade-detail/$id'
      path: '/trade-detail/$id'
      fullPath: '/trade-detail/$id'
      preLoaderRoute: typeof AuthenticatedTradeDetailIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommandCenterRoute: typeof AuthenticatedCommandCenterRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedMetafundRoute: typeof AuthenticatedMetafundRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStrategyProfilesRoute: typeof AuthenticatedStrategyProfilesRoute
  AuthenticatedTradeCreatorRoute: typeof AuthenticatedTradeCreatorRoute
  AuthenticatedValidatorRoute: typeof AuthenticatedValidatorRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedTradeDetailIdRoute: typeof AuthenticatedTradeDetailIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommandCenterRoute: AuthenticatedCommandCenterRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedMetafundRoute: AuthenticatedMetafundRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStrategyProfilesRoute: AuthenticatedStrategyProfilesRoute,
  AuthenticatedTradeCreatorRoute: AuthenticatedTradeCreatorRoute,
  AuthenticatedValidatorRoute: AuthenticatedValidatorRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedTradeDetailIdRoute: AuthenticatedTradeDetailIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
